### ISSUE TITLE
Can it be extended to custom Base URL?

### ISSUE THREAD

**Issue by ssoronid** [ryanto/next-s3-upload#101]
I would like to use this lib as it's super intuitive, but my usecase is that we have Contabo S3 Object Storage that URL is served different.

Maybe I didn't spot that option if it's already there, but would be super great if we can change it because Contabo supports S3 API. Here are [some docs](https://docs.contabo.com/docs/products/Object-Storage/HowTo/public-sharing) that pass an --endpoint-url parameter to connect via AWS CLI.

Example:

> aws --profile eu2 --endpoint-url https://eu2.contabostorage.com s3api put-bucket-policy --bucket foo --policy file://public-sharing-policy.json

Found what's happening after a couple of iterations trying to make it work and this compiled came from a file named: next-s3-upload.esm.js?2085

![image](https://user-images.githubusercontent.com/32467331/198934098-8696b5f8-76f8-4c4a-bd93-dc94157cdc45.png)

Also searched all the way in the source but couldn't make to get it. Maybe this [AWS SDK Doc ](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html)can help us with it.

By the way awesome tool you made, thanks for your time!

**Comment by ryanto** [comment]
Hey thanks for the issue! Quick question: Are you trying to upload files to a webhost that's not amazon?

**Comment by ssoronid** [comment]
Yes, Contabo works as amazon with the s3 api, only thing we should do is
point the host to the right one and everything will work.

Already tested with aws sdk and worked perfectly fine.

**Comment by ryanto** [comment]
Ok cool and thanks for the info. Right now this library doesn't work with non AWS hosts, even if they support the S3 API. We rely on the aws STS library and that is only support by AWS at this moment.

I think your best bet is using the aws-sdk directly if you're using a non amazon host.

Hopefully we can add support for other webhosts in the future!

**Comment by ryanto** [comment]
Going to close but please let me know if you need any help!
