### ISSUE TITLE
Adding metadata

### ISSUE THREAD

**Issue by Klaudioz** [ryanto/next-s3-upload#103]
Hi, and thank you for developing this.

I'd like to know if there is a way to add metadata to the folder created in the upload or for each of the files.

Thank you.

**Comment by ryanto** [comment]
Hi there! Right now this library doesn't support metadata, you'd have to do it by hand using something like the aws-sdk.

I'd love to hear more about what kind of metadata you'd like to add. Can you give me an example?

**Comment by Klaudioz** [comment]
I just want to add any text because I'm planning to have a daemon checking for the mounted S3 bucket, and this text will be the parameters of the process.

I don't know if I can do it using headers.

**Comment by ryanto** [comment]
Gotcha, that sounds like it would be out of scope for this library. I'd recommend using the aws-sdk to control object metadata in your bucket. Check out the docs here: https://aws.amazon.com/sdk-for-javascript/
