### ISSUE TITLE
TypeError: context.endpoint is not a function

### ISSUE THREAD

**Issue by arpecop** [ryanto/next-s3-upload#104]
![Screenshot 2022-11-08 at 11 56 11](https://user-images.githubusercontent.com/168974/200533961-cdf02a09-a82a-4ac2-9dde-0f56b2a5c2ab.png)

**Comment by ryanto** [comment]
Hey there! Thanks for the issue!

You can try `0.2.5`, which has recently upgraded the AWS dependencies. Let me know if the problem still persists.
