### ISSUE TITLE
Possibility to use Curl to upload files and json data?

### ISSUE THREAD

**Issue by seans98** [ryanto/next-s3-upload#112]
Hi @ryanto thanks again for creating this library! I was wondering if its possible with this library to upload files and the json data strictly using the endpoint via curl or postman? Or does it always have to be uploaded via the frontend? Thanks !

**Comment by ryanto** [comment]
Hi @seans98 !

This library was made for the frontend. If you're wanting to upload using curl I think you'll be better served finding a guide for using S3 with curl.

**Comment by ryanto** [comment]
Hey @seans98 I'm going to close this issue, but please feel free to comment if you're still running into any trouble!
