### ISSUE TITLE
Return ID of upload files and sync with db to preview files on different formats

### ISSUE THREAD

**Issue by ssoronid** [ryanto/next-s3-upload#117]
We're experimenting with the library so far and we could make it work to upload on different folders depending on userName Metadata.

What we would like to do now is to sync with db or retrieve fileName so users can preview the files but we are totally lost on how to solve this.

Our use-case is that users upload mp3 or wav files and they should preview later when files are upload in the UI.

What should be a good practice to approach on the solution?

Thanks in advance.

**Comment by ryanto** [comment]
I think the best way to go about this would be write the key to the database using an API route after the upload completes. Something like this:

```jsx
import { useS3Upload } from "next-s3-upload";

export default function UploadComponent() {
  let { FileInput, openFileDialog, uploadToS3 } = useS3Upload();

  let handleFileChange = async file => {
    let { key } = await uploadToS3(file);

    // write key to database via API route
    fetch("/api/write-key-to-database", {
      method: "POST",
      body: JSON.stringify({ key });
    });
  };

  return (
    <div>
      <FileInput onChange={handleFileChange} />

      <button onClick={openFileDialog}>Upload file</button>
    </div>
  );
}
```

The `key` is the path of the file on S3. Once you save it in the DB you should be able to rebuild the URL at any point in the future!

Hopefully that makes sense, but let me know if it doesnt.

**Comment by ryanto** [comment]
Hey @ssoronid haven't heard back from you so I'm going to close this issue. Feel free comment or reopen if you're still running into any problems!
