### ISSUE TITLE
How to have different bucket?

### ISSUE THREAD

**Issue by kacak9229** [ryanto/next-s3-upload#118]
Currently, the settings only allow one bucket, I need to use 3 buckets

1. for cover photo
2. text editor like StackOverflow editor
3. Upload any files

` const { uploadToS3 } = useS3Upload();` is using one bucket only

Just wondering whether its possible. Thanks ryanto for creating this amazing library, will donate!

**Comment by ryanto** [comment]
Yup it's possible, just not documented! Just note that AWS does technically limit the number of buckets you can have, so you're probably better off using one bucket with sub folders for each the uploads (/photos, /editor, /files, etc).

But if you want to use multiple buckets heres how:

First create a bunch of different api endpoints for each bucket. Like `/pages/api/photos-bucket.js` and `/pages/api/files-bucket.js`. Then add a bucket config for each of these API routes: https://next-s3-upload.codingvalue.com/bucket-config

Next, you can configure `useS3Upload` to use the bucket details from a specific API route. See this issue for more info: https://github.com/ryanto/next-s3-upload/issues/83

**Comment by kacak9229** [comment]
Thanks for the quick reply, i realized that although I already configured on the `/pages/api/files-bucket.js` , it will complain saying that I need `S3_UPLOAD_BUCKET`

```
// pages/api/files-bucket.js
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  accessKeyId: process.env.S3_UPLOAD_KEY,
  secretAccessKey: process.env.S3_UPLOAD_SECRET,
  bucket: process.env.S3_UPLOAD_BUCKET_FILES,
  region: process.env.S3_UPLOAD_REGION,
});
```

**Comment by ryanto** [comment]
Can you double check and make sure that `process.env.S3_UPLOAD_BUCKET_FILES` is defined. Maybe console.log it in the file.

**Comment by kacak9229** [comment]
Yeah already defined, i console.log it

`example-cloudfront-v1`
![Screenshot 2022-12-15 at 11 16 26 PM](https://user-images.githubusercontent.com/2588948/207897691-d6417a71-7c19-4ba0-bc26-8b2c5fe6e897.png)

**Comment by ryanto** [comment]
Hmm, what version of `next-s3-upload` are you using?

**Comment by kacak9229** [comment]
This is the version `"next-s3-upload": "^0.2.4",`

**Comment by ryanto** [comment]
I think that's the problem. Support for multiple buckets and env config was added recently. Try upgrading to `0.2.8`.

**Comment by kacak9229** [comment]
Okay nice! thanks really appreciate the fast reply.

By the way, I'm using s3 together with cloudfront and do i still need to unblock the public access right from my s3 bucket?

**Comment by ryanto** [comment]
You can block public access if you're using cloudfront. Just note that the `url` returned by `uploadToS3()` won't work because it's not public, but your cloudfront URLs will work since they can access files in non-public buckets.

Blocking public access + Cloudfront is how I'd recommend setting up your bucket :)

**Comment by kacak9229** [comment]
Oh I see, but Uploading the object won't work right since I already block the public access on my s3 bucket?

```
// pages/api/s3-upload.js
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  key(req, filename) {
    return `my/uploads/path/${filename.toUpperCase()}`;
  }
});
```
I should change this path to my cloudfront path right? `my/uploads/path/${filename.toUpperCase()}`

**Comment by ryanto** [comment]
Uploading an object should work for private buckets. 

The key function is the full path on S3, put whatever you want there. Then allow your cloudfront config to read from the path.

Btw, there's nothing wrong with public buckets for public updates. The cloudfront setup works, but it's an extra layer. Totally fine to use a public bucket.

**Comment by kacak9229** [comment]
Okay thanks for the quick response!

**Comment by kacak9229** [comment]
I'm doing something like this instead, it's a bit hacky

` const { url } = await uploadToS3(file);`

 const completeURL = url.replace(
        "https://examples.3.us-east-1.amazonaws.com/",
        "https://example.cloudfront.net/"
      );

**Comment by ryanto** [comment]
Very cool, happy to hear it's working!

There's a key variable that might be easier to use?

```js
const { key } = await uploadToS3(file);
const url = `https://example.cloudfront.net/${key}`;
```

**Comment by ryanto** [comment]
Hey @kacak9229 hopefully you got everything working. I'm going to close this issue, but leave a comment if you're still running into any issues.

**Comment by manuelsechi** [comment]
Hello,
sorry if I jumo in in this thread, I am a bit confised

I defined 2 endpoints, one for a public bck and one for a private one
se-public.js
`import {APIRoute} from "next-s3-upload";

export default APIRoute.configure({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    bucket: process.env.AWS_PUBLIC_BUCKET,
    region: process.env.AWS_REGION,
    key(req, filename) {
        return `${filename}`;
    }
});`

s3-private.js
`import {APIRoute} from "next-s3-upload";

export default APIRoute.configure({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    bucket: process.env.AWS_PRIVATE_BUCKET,
    region: process.env.AWS_REGION,
    key(req, filename) {
        return `${filename}`;
    }
});`

now, how should I refer to one or the other in my code?
atm I am doing 
`
import {useS3Upload} from "next-s3-upload";
let {uploadToS3, files} = useS3Upload();
`

thank you
M
