### ISSUE TITLE
Using two separate File Inputs

### ISSUE THREAD

**Issue by Tucker2015** [ryanto/next-s3-upload#119]
Hi, Wondering if it is possible to have two separate inputs as shown in the image.

I want to be able to add a Cover image and an MP3 file to my post.

I am using Firebase to store the urls.

I can get one input to upload and send the url to Firestore.

Thanks for any help.

![318645488_10159245311485197_398281275192578749_n](https://user-images.githubusercontent.com/16142165/208095850-e9ba0fd2-646c-4331-ad5d-c7ca29b5465d.jpg)

**Comment by ryanto** [comment]
Yup this should work! 

I'd recommend starting with two `<input>` tags that each of their own onChange handler. See the docs here: https://next-s3-upload.codingvalue.com/custom-file-input

Let me know if you run into any trouble.

**Comment by Tucker2015** [comment]
Thanks, I seemed to have done it using :

```
let handleTrackChange = async (track: File) => {
        let { url } = await uploadToS3(track);
        setTrackUrl(url);
        setFormData({ ...formData, trackUrl: url });
    };

let handleImageChange = async (image: File) => {
        let { url } = await uploadToS3(image);
        setTrackImage(url);
        setFormData({ ...formData, trackImage: url });
    };
```

Now to figure out how to save in separate folders.

**Comment by ryanto** [comment]
Take a look at the `key` function as a way to set the upload's folder: https://next-s3-upload.codingvalue.com/s3-file-paths

**Comment by Tucker2015** [comment]
Thank you, all working great now.

**Comment by ryanto** [comment]
Glad to hear! I'm going to close this but feel free to comment if you run into anything else.
