### ISSUE TITLE
 I have a Question for about 404 error 

### ISSUE THREAD

**Issue by jinsujj** [ryanto/next-s3-upload#12]
Hello! My name is Jinsu. Thanks for make this library it's easy and awesome!. 
Nowadays I make a new side project with my friends. and we'll going to use this library for - image upload   (Next.js - S3 - Vercel) 

When i Test this function in localhost it's work fine,  but in production didn't work with 404 error.
Can i know how to solove this ? 

The code is same with each other. so this issue seems like env settings..  May be IAM problem..  (not sure) 
I'd appreciate it if you could answer. Thanks for Read this issue and supporthing! .

**[localhost]**
![image](https://user-images.githubusercontent.com/19955904/123264407-f9268900-d534-11eb-9fe3-43b4aeedc191.png)

**[bucky site (404 Error!!!) ]** 
![image](https://user-images.githubusercontent.com/19955904/123264419-fcba1000-d534-11eb-8738-2f46583d99d3.png)

 **[S3 Settings]**

- **[policy]**
 ![image](https://user-images.githubusercontent.com/19955904/123266655-325ff880-d537-11eb-94ee-b3d8bf6ed0ea.png)
- **[cors]**
![image](https://user-images.githubusercontent.com/19955904/123266707-3be96080-d537-11eb-841f-9864e5e38035.png)

**[IAM Setting]**

- (User: "next_s3_upload"  as Programmatic access.)
![image](https://user-images.githubusercontent.com/19955904/123267443-faa58080-d537-11eb-9385-c6a2467f159a.png)

- (Policy)
![image](https://user-images.githubusercontent.com/19955904/123267806-5e2fae00-d538-11eb-96f7-0a554df1eae6.png)

**Comment by ryanto** [comment]
Hi Jinsu!

It looks like you're getting a 404 with the Next.js API route.

<img width="437" alt="Screen Shot 2021-06-24 at 3 05 14 PM" src="https://user-images.githubusercontent.com/89411/123318785-9a91e880-d4fd-11eb-9d01-2dcfeb656089.png">

Can you confirm that `/pages/api/s3-upload.js` exists and it is accessible via `https://www.bucky.co.kr/api/s3-upload`?

**Comment by jinsujj** [comment]
Hello ryanto. 
I found that In next.config.js .we use rewrites for all path. to backend server.. 

But i Thought that this api is not operated by backend(Spring) server. just here (front-end).
So I changed this source to below.  and hoped to work. 

But it happend other error log..  Could you tell me how i change this enviorment setting?

**[As-Is]**
![image](https://user-images.githubusercontent.com/19955904/123412230-56314600-d5ec-11eb-85ca-bb179063fcb8.png)


**[To-Be]**
![image](https://user-images.githubusercontent.com/19955904/123412235-5893a000-d5ec-11eb-96e9-52b6a4303928.png)



**[Result]**
![image](https://user-images.githubusercontent.com/19955904/123412418-87aa1180-d5ec-11eb-94e5-dc3635df5d79.png)

**Comment by hjkdw95** [comment]
Hello, @ryanto. I just got the same 404Error as Jinsu got.
(Works well via localhost, but went wrong when running it via real server)
Could you check it out if there's any missing or errors on my settings?

**next.js.config**
```
async rewrites() {
    if (process.env.NODE_ENV !== 'production') {
      return [
        {
          source: '/api/:path*',
          destination: `${process.env.NEXT_PUBLIC_SERVER_END_POINT}/api/:path*`,
        },
      ]
    }
```




`pages/api/s3-upload.ts` is existing and I got below errors while reaching directly via browser
![스크린샷 2022-04-26 오후 3 20 45](https://user-images.githubusercontent.com/76423949/165234847-94136a68-1a58-43d3-838a-044a85f668bd.png)

Many Thanks✨
