### ISSUE TITLE
set ACL when uploading

### ISSUE THREAD

**Issue by zebapy** [ryanto/next-s3-upload#122]
First off, thanks for a streamlined package for this use case! 

I'm trying to use digitalocean for storage with this but having problems setting a default access policy for my bucket. All my files are getting set as private by default. 

From what I can tell, the easiest option might be being able to pass ACL param when uploading. This would mean no one has to fuss with CLIs to set policies for the digitalocean Space. 

From example on here
https://docs.digitalocean.com/reference/api/spaces-api
the ACL param can be set when uploading:
```js

// Step 3: Define the parameters for the object you want to upload.
const params = {
  Bucket: "example-space", // The path to the directory you want to upload the object to, starting with your Space name.
  Key: "folder-path/hello-world.txt", // Object key, referenced whenever you want to access this file later.
  Body: "Hello, World!", // The object's contents. This variable is an object, not a string.
  ACL: "private", // Defines ACL permissions, such as private or public.
  Metadata: { // Defines metadata tags.
    "x-amz-meta-my-key": "your-value"
  }
};
```

Looking at the code, it doesn't appear there's any sort of config/param I can set currently 
https://github.com/ryanto/next-s3-upload/blob/a3457c05515cda43e2e27733257a780413fb5ba2/packages/next-s3-upload/src/pages/api/s3-upload.ts#L53-L62
Do you have suggestions on how to handle this?

**Comment by zebapy** [comment]
Oh actually my policy I set through CLI worked I think. 

I used this. Change `BUCKET_NAME` and endpoint as needed. 

```aws --endpoint-url=https://nyc3.digitaloceanspaces.com s3api put-bucket-policy --bucket=BUCKET_NAME --policy file://policy.json
```

policy.json
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": ["s3:GetObject"],
      "Resource": ["arn:aws:s3:::BUCKET_NAME/*"]
    }
  ]
}
```

Also had to run `aws configure` first to authenticate. It asks for access key and secret, which folks should have if they followed this project's setup docs or set up a Space on digitalocean.

**Comment by ryanto** [comment]
Awesome, glad to hear you got it working!

To answer your original question about ACLs I believe AWS is moving away from these with bucket storage, so I doubt this library will support them.

**Comment by ryanto** [comment]
Hey @zebapy I'm going to close this, but let me know if you run into anything else!
