### ISSUE TITLE
cors with cloudflare R2

### ISSUE THREAD

**Issue by justTreme** [ryanto/next-s3-upload#123]
I'm trying to use next-s3-upload with a cloudflare r2 bucket. 
Anyone has experience with this?

Here is my `/api/s3-upload`:
```javascript
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
    accessKeyId: process.env.S3_ACCESS_KEY,
    secretAccessKey: process.env.S3_SECRET_KEY,
    bucket: process.env.S3_BUCKET_NAME,
    region: "auto",
    endpoint: process.env.S3_ENDPOINT,
    forcePathStyle: true,
});
```

This is my frontend page:
```javascript
import { PageHead } from "../components/pageHead";
import { useState } from "react";
import { usePresignedUpload } from "next-s3-upload";

export default function Home() {
    let { uploadToS3, FileInput, openFileDialog } = usePresignedUpload();
    const [image, setImage] = useState<string>("");

    const handleFileChange = async (file: File) => {
        let { url } = await uploadToS3(file);
        setImage(url);
    };

    return (
        <>
            <PageHead title={"Home"} />

            <main>
                <span>Hello World</span>
                <FileInput onChange={handleFileChange} />

                <button onClick={openFileDialog}>Upload file</button>

                {image && <img src={image} />}
            </main>
        </>
    );
}
```

My upload gets rejected by cors. Is there anyone who is using cloudflare R2 and know how to access the files / upload new files?

Thanks!

**Comment by zebapy** [comment]
Did you google anything like "configure CORS for cloudflare R2"? 
Here's some result I found which may lead you in right direction https://kian.org.uk/configuring-cors-on-cloudflare-r2/

**Comment by justTreme** [comment]
> Did you google anything like "configure CORS for cloudflare R2"? Here's some result I found which may lead you in right direction https://kian.org.uk/configuring-cors-on-cloudflare-r2/
> 
> Sorry I know saying "google it" is not helpful but Im sure folks want to be sure you took a step like this. You likely need to configure the CORS settings for cloudflare.

Thanks for your reply. Yes, I already looked it up on google. I even found the same tutorial you send me.
The response i get back from it is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>MalformedXML</Code>
    <Message>The XML you provided was not well formed or did not validate against our published schema.</Message>
</Error>
```

**Comment by ryanto** [comment]
Cloudflare makes it really hard to configure CORS. You have to do it all from API requests.

Here's the script I used to configure CORS: https://github.com/ryanto/next-s3-upload/blob/master/packages/docs-site/scripts/cloudflare-cors.mjs

Make sure you have all the ENV variables defined.

**Comment by justTreme** [comment]
> Cloudflare makes it really hard to configure CORS. You have to do it all from API requests.
> 
> Here's the script I used to configure CORS: https://github.com/ryanto/next-s3-upload/blob/master/packages/docs-site/scripts/cloudflare-cors.mjs
> 
> Make sure you have all the ENV variables defined.

Thanks, that worked out for me

**Comment by deadcoder0904** [comment]
i'm facing the same issue.

where do i put the `cors` variables? which file specifically?

**Comment by deadcoder0904** [comment]
i did try putting this in my cors policy settings on cloudflare:

```json
[
  {
    "AllowedOrigins": [
      "http://localhost:3000"
    ],
    "AllowedMethods": [
      "GET",
      "PUT",
      "POST",
      "HEAD",
      "DELETE"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "ExposeHeaders": [],
    "MaxAgeSeconds": 3000
  }
]
```

and it did upload the file but i get errors on previewing the image.

the get request somehow isn't working. i get 400 bad request error.

**Comment by deadcoder0904** [comment]
i have these 2 disabled. might be an issue. i'll configure it & let you know:

<img width="340" alt="image" src="https://github.com/ryanto/next-s3-upload/assets/16436270/c1d9656e-d7cf-4f65-a586-8d3fe47db9c4">

**Comment by deadcoder0904** [comment]
appreciate the help but the link i posted has the solution 💯 

this library worked too but i needed a `download` method as well so i went with `@aws-sdk/client-s3` & next 13's `app/` directory.
