### ISSUE TITLE
Custom provider

### ISSUE THREAD

**Issue by tonxxd** [ryanto/next-s3-upload#124]
Hi, it seems i cannot use a custom endpoint without presigned urls.
I tried to set the following env variables

```
S3_UPLOAD_KEY=****
S3_UPLOAD_SECRET=****
S3_UPLOAD_BUCKET=bucketname
S3_UPLOAD_REGION=fr-par
S3_UPLOAD_ENDPOINT=https://bucketname.s3.fr-par.scw.cloud
```

And configure the route
```js
// pages/api/s3-upload.js
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  accessKeyId: process.env.S3_UPLOAD_KEY,
  secretAccessKey: process.env.S3_UPLOAD_SECRET,
  bucket: process.env.S3_UPLOAD_BUCKET,
  region: process.env.S3_UPLOAD_REGION,
  endpoint: process.env.S3_UPLOAD_ENDPOINT,
});
```

But i get
<img width="522" alt="Screenshot 2022-12-29 alle 13 50 50" src="https://user-images.githubusercontent.com/2827496/209953535-93502ef9-42bc-4e17-9b20-d7b5fc505f7c.png">

If i use `usePresignedUpload` it returns 200 but the file is not actually stored in the bucket, if i use `useS3Upload` the request fails..
Does it mean custom providers only work using the presigned url approach?
It seems that on line `https://github.com/ryanto/next-s3-upload/blob/master/packages/next-s3-upload/src/pages/api/s3-upload.ts#L72` the library does not take into account the custom endpoint in case of non url presigned uploads

**Comment by tonxxd** [comment]
It says in the documentation i have to use presigned urls, closing, thanks.
https://next-s3-upload.codingvalue.com/other-providers

**Comment by ryanto** [comment]
Ok cool. Yup customer providers can only used presigned uploads. 

Were you able to get presigned working?

**Comment by tonxxd** [comment]
Partially, i had to fork and edit https://github.com/ryanto/next-s3-upload/blob/master/packages/next-s3-upload/src/hooks/use-presigned-upload.ts#L31 since the result url was not following the format in the source code (it is of type https://{bucketname}.s3.fr-par.scw.cloud/{key}
Also there was an issue with bucket CORS (returning 403) not related to the library.. maybe it's helpful for someone else to know

**Comment by ryanto** [comment]
Gotcha, are you using this provider: https://www.scaleway.com/en/object-storage/ ?
