### ISSUE TITLE
How to upload different files in different buckets?

### ISSUE THREAD

**Issue by manuelsechi** [ryanto/next-s3-upload#126]
Is there a way to determine where to upload a file? For example, can I upload a file to a bck and another one, from a different form, to another bck?

**Comment by ryanto** [comment]
Hi @manuelsechi Yup, you can use multiple buckets. Check out the answer here: https://github.com/ryanto/next-s3-upload/issues/118#issuecomment-1351940260

**Comment by ryanto** [comment]
Hopefully you got this working, but let me know if not!

**Comment by manuelsechi** [comment]
Hey, sorry if I didn't reply. Yes I made it work, thanks for your help.
