### ISSUE TITLE
How can I use non-english filename to custom path?

### ISSUE THREAD

**Issue by Kim-Jiseong** [ryanto/next-s3-upload#128]
@@//s3-upload.ts
import { APIRoute } from "next-s3-upload";
export default APIRoute.configure({
  key(req, filename) {
    return `customPath/${filename}`;
  },
});

------------
I tried to upload file with non-english filename and it makes an error like this. If I upload file with english filename, It works well.

STSServiceException [ValidationError]: 1 validation error detected: Value '{"Statement":[{"Sid":"Stmt1S3UploadAssets","Effect":"Allow","Action":["s3:PutObject"],"Resource":["arn:aws:s3:::my-bucket-name/customPath/테스트.docx"]}]}' at 'policy' failed to satisfy constraint: Member must satisfy regular expression pattern: [\u0009\u000A\u000D\u0020-\u00FF]+

How can I solve it?

**Comment by ryanto** [comment]
Thanks for the issue!

Unfortunately, S3 only supports english keys. Check out these docs for the recommended characters: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

You can use the `sanitizeKey` from this library to ensure the filename is a safe key name.

```js
import { APIRoute, sanitizeKey } from "next-s3-upload";

export default APIRoute.configure({
  key(req, filename) {
    return `customPath/${sanitizeKey(filename)}`;
  },
});
```

**Comment by ryanto** [comment]
Hey @Kim-Jiseong I haven't heard from you so I'm going to close this issue. However, let me know if you're still running into any issues with this.
