### ISSUE TITLE
Getting error in s3-upload.js

### ISSUE THREAD

**Issue by vinitkumargoel** [ryanto/next-s3-upload#129]
Versions
"next-s3-upload": "0.2.9",
"next": "^13.1.6",
"aws-sdk": "^2.1306.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",

s3-upload.js
`export { APIRoute as default } from "next-s3-upload";
`

<img width="1440" alt="Screenshot 2023-02-01 at 9 59 12 PM" src="https://user-images.githubusercontent.com/18486917/216103344-6bb494d7-fa04-43ef-a327-808663a6bcff.png">

**Comment by ryanto** [comment]
Can you share the client side code that's performing the upload?

**Comment by ryanto** [comment]
Hey @vinitkumargoel I haven't heard from you so I'm going to close this issue. Let me know if you're still running into an issue here.
