### ISSUE TITLE
Delete Image

### ISSUE THREAD

**Issue by blazestudios23** [ryanto/next-s3-upload#13]
Hey it would be awesome if you could add a delete image feature to this. Or maybe I could add it. Would need to look at this repo more.

**Comment by ryanto** [comment]
Hey there, interesting idea!

How do you imagine delete file working? Any pseudo or sample code you can share? Would love to hear more.

**Comment by ryanto** [comment]
Hi @blazestudios23 Haven't heard from you... I'm going to close this issue, but feel free to reopen if you want to provide the use case or an example of the API you'd like to see for deleting a file.

**Comment by blazestudios23** [comment]
Sorry, I forgot to respond.

I just implemented it like this in my app:

```
import { NextApiHandler } from 'next';
import { getB2S3Client, getB2 } from '../../../utils/b2';

const deleteImage: NextApiHandler = async (req, res) => {
  try {
    const { uri } = req.body;
    if (!uri) return res.status(400).send('No Image');
    let fileName: string;
    if (uri.split('/').includes('video')) {
      fileName = `video/${uri.substring(uri.lastIndexOf('/')).substring(1)}`;
    } else {
      fileName = uri.substring(uri.lastIndexOf('/')).substring(1);
    }

    // console.log(imageUrl.substring(imageUrl.lastIndexOf('/')).substring(1));

    // console.log('fileName', fileName);

    const b2 = await getB2();
    const auth = await b2.authorize();
    // console.log('auth', auth.data);

    const params = {
      Bucket: auth.data.allowed.bucketName,
      Prefix: fileName
    };

    const s3 = getB2S3Client();

    let fileId: string | undefined;

    s3.listObjectVersions(params, async (err, data) => {
      if (err) {
        console.log(err);
        res.status(400).send('Delete Failed');
      }

      const version = data?.Versions?.[0];
      fileId = version?.VersionId;
      // res.send({ ok: true });
      if (fileId) {
        await b2.deleteFileVersion({
          fileId,
          fileName
        });
        return res.send({ ok: true });
      } else {
        return res.status(400).send('No fileId');
      }
    });
  } catch (e) {
    console.log('Error Message', e.response.data);

    return res.status(500).send('Image Not Deleted.');
  }
};

export default deleteImage;



```

**Comment by tatimblin** [comment]
If this worked by adding ‘deleteImage’ to the s3-upload request similar to ‘filename’, and trying to delete an image at that path it would be really useful. Would solve any time you want a single image at a time per entity, like a users profile picture, or editing an existing post

**Comment by blazestudios23** [comment]
> If this worked by adding ‘deleteImage’ to the s3-upload request similar to ‘filename’, and trying to delete an image at that path it would be really useful. Would solve any time you want a single image at a time per entity, like a users profile picture, or editing an existing post

This is exactly what I'm doing.

**Comment by ryanto** [comment]
Great stuff @blazestudios23! Thanks for replying.

Right now I think it's best to keep this code in user/app space like you've don (instead of the addon). If anyone asks how to delete an image I'll send them to your example.

Thanks again!
