### ISSUE TITLE
Return result so it can be stored in the database

### ISSUE THREAD

**Issue by adpopescu338** [ryanto/next-s3-upload#130]
I appreciate how easy it is to setup and endpoint with one line one, nonetheless it's not easily possible to store the result in the database before sending the response.

I found this workaround but ideally an simple function to handle the upload and return the results should be exposed.

export const upload = (req: NextApiRequest) =>
  new Promise((resolve) => {
    APIRoute(req, {
      status: (code) => {
        return {
          json: (data) => resolve(data),
        };
      },
    } as unknown as NextApiResponse);
  });

**Comment by ryanto** [comment]
Thanks for the issue! 

I'd recommend having the React app make another API request to a different api route after the upload completes. The problem with overriding `status` and `json` is that the upload hasn't completed at that point, so you could be writing a record to the database for an upload that failed (or never happened).

**Comment by ryanto** [comment]
Hey @adpopescu338 haven't heard from you so I'm going to close this issue. Feel free to comment if you're still running into any problems.
