### ISSUE TITLE
Support for multiple image upload

### ISSUE THREAD

**Issue by OlivierJM** [ryanto/next-s3-upload#14]
Thanks for the awesome library, It makes it easy to work with s3 uploads,

It would be great to add support for uploading multiple images.

**Comment by Nautman** [comment]
Completely agree!

**Comment by ryanto** [comment]
Hey there, great suggestion!

While in the docs we only show how to do a single file upload, you can absolutely do multiple uploads using React!

Take a look at [this StackOverflow](https://stackoverflow.com/a/55831786), you add `multiple` to the file upload input https://stackoverflow.com/a/55831786 (you'll need to wire up your own `<input type="file">` input) and then you can loop over all the selected files and call `uploadToS3` on each of them.

We'll get some better docs around this, but for now I think the best approach to multiple file uploads would be building your own file input.

**Comment by OlivierJM** [comment]
Thanks a lot @ryanto I will try and wire up my own input and see it works. If it works I can send a PR to update the readme.

**Comment by OlivierJM** [comment]
@ryanto I tried your solution and it worked well, 

I have an input field that accepts multiple files
`<input type="file" name="file" multiple onChange={handleFileChange} />`  

Then inside my handleFileUploads, I have the following

```javascript
  const handleFileUploads = async ({ target }) => {
    setIsUploading(true)
    const urls = []
    const files = Array.from(target.files)

    for (let index = 0; index < files.length; index++) {
      const file = files[index]
      const { url } = await uploadToS3(file)
      urls.push(url)
    }
    setIsUploading(false)
    handleImagesUpload(urls)
  }
```

Let me know if it is worth updating the documentation to reflect this, I just wanted to put it here in case someone needs a similar implementation.

**Comment by ryanto** [comment]
Awesome stuff @OlivierJM!

Absolutely feel free to PR the docs adding this example! I'd love to see what you used for the `<input>` as well.

In the mean time I'll send anyone that asks about multiple uploads to your example.

Thanks again.

**Comment by OlivierJM** [comment]
@ryanto Thanks I have put up a PR in #17

**Comment by ryanto** [comment]
Awesome 🎉 

I'm going to close this issue since this is now in the docs. Thanks again @OlivierJM !

**Comment by OlivierJM** [comment]
Thanks too @ryanto
