### ISSUE TITLE
next env production

### ISSUE THREAD

**Issue by vinibgoulart** [ryanto/next-s3-upload#142]
I did deploy on vercel but I'm getting error 500 only in production. Do environment variables have to be prefixed with NEXT_PUBLIC_ or is it not necessary?

**Comment by ryanto** [comment]
Nope, they should not be prefixed. If you prefix them with NEXT_PUBLIC they become public variables, which would be bad since these are AWS private keys.

Vercel requires you to redeploy your app once you've changed an ENV variable. I'd try to redeploy and see if that fixes your problem.
