### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Aaris03K** [ryanto/next-s3-upload#148]
Hey @ryanto,

I get this issue often when i try to reload the page on my local. I have cross checked every env value and everything seems to be fine. Any idea why this keeps happening?

![Screenshot 2023-05-10 at 3 07 07 PM](https://github.com/ryanto/next-s3-upload/assets/113997462/625cd705-24d0-49a0-9516-94b67fa9735a)

**Comment by ryanto** [comment]
Hmm, sorry about that! Were you able to get it resolved? I'm not sure what's causing that, but it might help to try the latest version of next-s3-upload.

**Comment by Aaris03K** [comment]
Yes @ryanto, Upgrading the node version fixed the issue. not sure what happened there but we can close this issue.
