### ISSUE TITLE
API error 500: TypeError: Cannot read properties of undefined (reading 'replace') 

### ISSUE THREAD

**Issue by hedysnike** [ryanto/next-s3-upload#149]
https://i.imgur.com/MitjS6d.png
https://i.imgur.com/VO1Ne6F.png

**Comment by harshitdkanodia** [comment]
Suddenly getting the same error !

**Comment by harshitdkanodia** [comment]
So this was happening because I was passing the wrong object to uploadToS3, please ensure that you are passing the right file object ( the standard JS file object ) to the function

**Comment by wow056** [comment]
It also happens to me

**Comment by LamShiuChing** [comment]
Does anyone has a fix for this issue?

**Comment by ryanto** [comment]
Can you guys share code? Your React component and api route would be a good place to start.

**Comment by erfanium** [comment]
It's because app directory is not supported yet

**Comment by ryanto** [comment]
This should be fixed in `0.3.3`.
