### ISSUE TITLE
Bucket endpoint configuration error.

### ISSUE THREAD

**Issue by Theeeus** [ryanto/next-s3-upload#152]
I'm trying to edit the endpoint according to this example from the docs:

https://next-s3-upload.codingvalue.com/bucket-config
```
// pages/api/s3-upload.js
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  // ..
  endpoint: "https://my.endpoint",
  forcePathStyle: true
});
```

However, when I add this I get the following typescript error:

`Argument of type '{ endpoint: string; forcePathStyle: boolean; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'endpoint' does not exist in type 'Options'.`

**Comment by ryanto** [comment]
Hi @Theeeus were you able to get this resolved? If not can you confirm you're on the latest version of next-s3-upload?
