### ISSUE TITLE
Giving error http://localhost:3000/api/s3-upload 404 (Not Found) - Nextjs App Structure

### ISSUE THREAD

**Issue by studiolama** [ryanto/next-s3-upload#154]
I am using nextjs latest version with app directory structure but getting this error while uploading file. I have followed documentation as it is but it is not working

`http://localhost:3000/api/s3-upload 404 (Not Found)`
`Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

Please suggest any solution for it .

| Package name | Version |
|--------|--------|
| next | ^13.4.12 |
| next-s3-upload | ^0.3.0 |
| react | ^18.2.0 | 
| react-dom | ^18.2.0 |
| OS | MacOS 13.4.1 (22F82) |
| Browser | Chrome |

**Comment by Dangleburry** [comment]
Same issues with new default app router in Next.js

**Comment by martinmiglio** [comment]
The app router uses a different handler syntax for API routes than next-s3-upload provides.
Next 13.4 supports backwards compatibility with the page router, so you still need to put the route in `src/pages/api/s3-upload.js` as opposed to in the `app` dir. This API route will work seamlessly with pages on either router.

Supporting the app router would be a nice feature to have through.

**Comment by abhay-ramesh** [comment]
```ts
// app/api/s3-upload/route.ts

import { AppAPIRoute, sanitizeKey } from "next-s3-upload";

export APIRoute.configure({
  key(req, filename) {
    return `images/${sanitizeKey(filename)}`;
  },
}) as POST;
```

**Comment by ryanto** [comment]
@abhay-ramesh Wow that's great, can you confirm it works in your app?

**Comment by oussamajabnouni** [comment]
@abhay-ramesh The app router handler is different from page router, that didn't work for me.

**Comment by ryanto** [comment]
Ok app router is now supported in `0.3.4`! See setup here: https://next-s3-upload.codingvalue.com/setup#api-route-(app-router)

If anyone adds this to their app let me know how it goes or if you run into any issues.

**Comment by aamirl** [comment]
For anyone running into issues with trying to set up multiple buckets with the NextJS `app` router, this is what you need to put in your `app/api/{custom-route}/route.ts` file:

```
import { POST as post } from 'next-s3-upload/route';

export const POST = post.configure({
	async key(req, filename) {
		console.log(filename);
		return `images/${sanitizeKey(filename)}`;
	},
	accessKeyId: AppConfig.aws.s3.uploadKey,
	secretAccessKey: AppConfig.aws.s3.uploadSecret,
	bucket: AppConfig.aws.s3.uploadBucket,
	region: AppConfig.aws.s3.uploadRegion,
});
```

Replace the AppConfig with wherever the values are coming from, and now you can set up multiple routes and different buckets!
