### ISSUE TITLE
Method not allowed.

### ISSUE THREAD

**Issue by iceverge** [ryanto/next-s3-upload#159]
In new NextJS api path will be - "api/folder/route.js" - routable
So the path "api/s3-upload/".
It return error.

`export { APIRoute as default } from "next-s3-upload";`

Do you have new configuration using the current updated NEXTJS?

**Comment by ryanto** [comment]
Ok app router is now supported in `0.3.4`! See setup here: https://next-s3-upload.codingvalue.com/setup#api-route-(app-router)

If anyone adds this to their app let me know how it goes or if you run into any issues.
