### ISSUE TITLE
Require is not defined for aws-sdk on Next

### ISSUE THREAD

**Issue by beacoding** [ryanto/next-s3-upload#160]
Been getting the following on 

`next 13.4.19`
`next-s3-upload": "^0.3.0"`

````
Unhandled Runtime Error
ReferenceError: require is not defined

Call Stack
@aws-sdk/signature-v4-multi-region
```

**Comment by ryanto** [comment]
I would try upgrading to the latest version  (`0.3.4`) to see if that helps fix this error for you.
