### ISSUE TITLE
Region is missing error

### ISSUE THREAD

**Issue by weidezhang** [ryanto/next-s3-upload#163]
Hi, 

After I upgrade to   "next-s3-upload": "^0.4.0-rc1", I got the region is missing error even though I defined the S3_UPLOAD_REGION in .env config. Any idea why ? 

Here is some detailed log: 
`
[app]: error - Error: Region is missing
[app]:     at default (/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
[app]:     at /node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83
[app]:     at /node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
[app]:     at async coalesceProvider (/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
[app]:     at async node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28
`

**Comment by ryanto** [comment]
Hey, I think it's better to use the stable version: `0.3.2`

**Comment by weidezhang** [comment]
Hi @ryanto , I got the following when using 0.3.2. Any idea why it happens ? 

```
TypeError: Failed to fetch
    at FetchHttpHandler.handle (fetch-http-handler.js:56:1)
    at async eval (flexibleChecksumsResponseMiddleware.js:17:1)
    at async eval (deserializerMiddleware.js:2:24)
window.console.error @ next-dev.js:20
```

**Comment by ryanto** [comment]
Try upgrading to `0.3.3`, that should be fixed now. Sorry about that!

**Comment by ryanto** [comment]
Closing this but let me know if you're still running into any issues!
