### ISSUE TITLE
Verification Config

### ISSUE THREAD

**Issue by blazestudios23** [ryanto/next-s3-upload#18]
Can I see an example with a verification configuration where the size of the image and image type are checked from the API/imageUpload route.

**Comment by ryanto** [comment]
Hey @blazestudios23 I'm not sure this exists... can you give me an example of what you're trying to do and I'll try my best to answer :)

**Comment by blazestudios23** [comment]
I'm trying to run code like then when the api route is hit:

```
 if (mustBeSquare && notSquare) {
        setErrors('Image must be a square');
      } else if (tooSmallDimensions) {
        setErrors('Image height and width must be at least 256px');
      } else if (tooBigSize) {
        setErrors('File cannot be bigger than 1 MB');
      } else if (file) {
        setPreview(URL.createObjectURL(file));
        uploadFile({ variables: { file } });
      } else if (file.type !== 'image/png') {
        setErrors('File must be a .png');
      } else {
        setErrors('Something went wrong. Check file type and size (max. 1 MB)');
      }
```

**Comment by ryanto** [comment]
Is that frontend code? `URL.createObjectURL()` is a browser API, so you'll only be able to run this code on the client. You can then call `uploadToS3` once the checks have passed.

**Comment by blazestudios23** [comment]
That’s just an example. I’m trying to validate image size and and image type on the backend.

**Comment by ryanto** [comment]
Ah okay, gotcha!

So the way the S3 uploads work is the image file never touches your backend, it goes directly to S3.

Here are the steps that happen:

1. The bowser makes a request to your backend (the next-s3-upload route) asking to upload to S3.
2. next-s3-upload authorizes the browser to upload an image to a specific S3 key.
3. The browser uploads the file to S3 and gets back the URL from AWS.

If you wanted your backend to validate that the image is the right dimensions or size then you could take the URL, send it to your backend, and have the backend run some validation logic. Unfortunately, that's out of scope for this package, so you'd you have to build that out yourself. 

I'd recommend doing the validation client side (if you can). 

Hopefully that helps!

**Comment by blazestudios23** [comment]
I want to be able to validate the image with

pages/api/s3-upload.js

I want to be able to pass in a config do this to do the validation.

I currently have to write custom s3 uploads in pages/api. It would be nice to be able to use a plug to do so.

Best,

Andrew

**Comment by ryanto** [comment]
Yup I understand. Unfortunately, we won't be able to do it in this addon because we don't send the image to the server.

I'd recommend checking out some node packages like [image-size](https://github.com/image-size/image-size) and [image-type](https://github.com/sindresorhus/image-type) to do this type of validation in node.
