### ISSUE TITLE
500 error when uploading image file to S3

### ISSUE THREAD

**Issue by krjo** [ryanto/next-s3-upload#2]
Hi, first off thank you for putting this together. If I can get this to work this will be a huge time saver.

I went through the setup with no problems, and I've got my app deployed to production, and when I add an image file using the file upload element, I'm getting a 500 error and it's not uploading to S3:

```
GET https://pura-vida-admin-tools-ca.herokuapp.com/api/s3-upload?filename=sample-upload-image.jpg 500 (Internal Server Error)
VM25:1 Uncaught (in promise) SyntaxError: Unexpected token I in JSON at position 0
```

It's just a .jpg file. Any idea what the issue could be?

**Comment by krjo** [comment]
**face palm**, i didn't add my env variables to heroku, disregard!

**Comment by krjo** [comment]
This is working correctly, but I just wanted to call out that I'm still getting a 400 PUT error when the file uploads to S3, even though it still uploads successfully:

`PUT https://my-s3-bucket.s3.amazonaws.com/next-s3-uploads/6f361223-fd43-4ebc-9c32-34a29dcde944/sample-upload-image.jpg 400 (Bad Request)`

**Comment by ryanto** [comment]
Hey thanks for letting me know!

Are there any error messages also returned with the 400 request? If you want to share any an example or a link with me I can check it out.

Thanks!

**Comment by ryanto** [comment]
Hey @krjo I'm going to close this, but feel free to reopen if you have something to show me, more than happy to take a look.
