### ISSUE TITLE
Custom Path For Multiple Upload Types

### ISSUE THREAD

**Issue by ggmacasaet** [ryanto/next-s3-upload#27]
Hi,

 I would like to know if there's a support for example you  have 2 types of upload that will happen:

1.) Upload of Image should go to /images directory.
2.) Upload of CSV files should to /csvfiles directory.

Is there a way to separate that using single configuration?

**Comment by ryanto** [comment]
Yes, take a look at the `key` function. You can return a different path based on the file type.

https://github.com/ryanto/next-s3-upload#configuring-uploads

**Comment by baronnoraz** [comment]
The URL has changed.  For anyone interested...

[https://next-s3-upload.codingvalue.com/s3-file-paths](https://next-s3-upload.codingvalue.com/s3-file-paths)
