### ISSUE TITLE
Cannot upload image in production on Heroku

### ISSUE THREAD

**Issue by heteibako** [ryanto/next-s3-upload#29]
I have deployed a Next Js app on Heroku.
In development I can upload images to the s3 bucket but not in production.
I have checked the env variables in my Heroku dino. I am using the same vars as in dev.

When I am uploading the image I get only a 200 GET request but the PUT request never happens.
Do I need to add any other env variables other than these?
Thanks for you answer.

S3_UPLOAD_KEY
S3_UPLOAD_SECRET
S3_UPLOAD_REGION
S3_UPLOAD_BUCKET

 "next": "^12.0.3",
 "next-s3-upload": "^0.1.7",

**Comment by ryanto** [comment]
That looks right. Looks like we'll need more info to debug this.

- Are any errors returned in the network tab?
- Do you have an example link where the upload can be tested?

**Comment by heteibako** [comment]
Hi Ryan. Thanks for getting back to me. 

Answering your questions, 
1. No errors returned. Only a 200 GET request happens

<img width="1060" alt="Screenshot 2021-11-12 at 22 09 47" src="https://user-images.githubusercontent.com/19397150/141535115-991de9d5-20d5-45c1-a840-f347742b966b.png">
2.  I will send you a link to the test app's admin page and will remove the auth for that particular route.

**Comment by heteibako** [comment]
@ryanto Quick update. The issue was on my side. I forgot to add en env var to the next config file.
Sorry. You can close this issue.

**Comment by ryanto** [comment]
Hey @heteibako, glad to hear you got it working!
