### ISSUE TITLE
Cant handle progress of file being uploaded 

### ISSUE THREAD

**Issue by sulesuleman** [ryanto/next-s3-upload#30]
Can we show progress of file while its uploading on S3?

**Comment by ryanto** [comment]
Yup, absolutely... it's just not documented very well, sorry about that!

```js
let { uploadToS3, files } = useS3Upload();

console.log(files); // files is an array of the files you've uploaded.
```

As you start uploading files you'll see that `files` array populate with the uploaded files. In there is each file's progress.

**Comment by ryanto** [comment]
I updated the docs with an example of file progress: https://next-s3-upload.codingvalue.com/tracking-progress

Going to close this but please comment if anyone runs into any sort of trouble.

**Comment by juvaly** [comment]
> @ryanto 👋 Progress kind of works for me, but only display 0 or 100, not the in-between numbers... I'm wondering where it comes from, do you have an idea ?

Same here. 0 to 100. Real quick.

**Comment by cheung-chifung** [comment]
same issue
