### ISSUE TITLE
Env vars are not being recognised

### ISSUE THREAD

**Issue by justinphilpott** [ryanto/next-s3-upload#32]
Context: 
AWS Amplify, 
node v.14
NextJS 12

I am consistently receiving the following error from Next-s3-upload:

`Next S3 Upload: Missing ENVs S3_UPLOAD_KEY, S3_UPLOAD_SECRET, S3_UPLOAD_REGION, S3_UPLOAD_BUCKET`

I have logged the values into Cloudwatch logs from within the lambda that handles the file upload:

```
// pages/api/s3-upload.js
import { APIRoute } from 'next-s3-upload';

console.log('S3_UPLOAD_KEY', process.env.S3_UPLOAD_KEY);
console.log('S3_UPLOAD_SECRET', process.env.S3_UPLOAD_SECRET);
console.log('S3_UPLOAD_BUCKET', process.env.S3_UPLOAD_BUCKET);
console.log('S3_UPLOAD_REGION', process.env.S3_UPLOAD_REGION);

export default APIRoute.configure({
  key(req, filename) {
    return `inputs/${filename}`;
  },
});
```

and they prove that the values are actually available within the lambda, I won't include here as they are of course secrets. 

I don't understand why this library is not picking this up, especially as it WORKS locally..... any clues anyone?

**Comment by ryanto** [comment]
Ok this one sure is strange! Did you manage to get it fixed?

Currently the code we use to check for the ENVs is here:  https://github.com/ryanto/next-s3-upload/blob/master/src/pages/api/s3-upload.ts#L75-L83

You could try copying this code into your own API route handler and seeing the result. something like this...

```js
// pages/api/test-missing-env.js

let missingEnvs = () => {
  let keys = [
    'S3_UPLOAD_KEY',
    'S3_UPLOAD_SECRET',
    'S3_UPLOAD_REGION',
    'S3_UPLOAD_BUCKET',
  ];
  return keys.filter(key => !process.env[key]);
};

export default function(req, res) {
  res.status(200).json({ missing: missingEnvs() });
}
```

This might help you debug if other API routes are also having trouble accessing ENV vars.

**Comment by justinphilpott** [comment]
Crazy thing is I could output the env vars themselves from the lambda (deployed by Amplify), and I checked in cloudwatch , and there they were, so they were clearly within scope. The library worked locally, but NOT when deployed on Amplify.

**Comment by ryanto** [comment]
Right, I understand. Amplify, Lamda, and Cloudwatch are opaque to us so I'd like to simplify as much of this as possible. My suggestion would be to start with the `pages/api/test-missing-env.js` debug route so we can see if lamda can return the ENVs. This cuts Cloudwatch out of the equation and is one less thing for us to debug :)

I'm guessing the API route that returns the ENVs still won't work, but it helps us simplify.

**Comment by ryanto** [comment]
Hey just wanted to check-in on this issue, did you end up figuring anything out? 

I did a search and it looks like there's some issues with ENVs, Next, and Amplify. Checkout this issue for more details: https://github.com/aws-amplify/amplify-console/issues/1987

**Comment by ryanto** [comment]
Hey there! Haven't heard back so I'm going to close this issue.

If anyone is still running into this feel free to comment.

**Comment by ryanto** [comment]
Version `0.1.8` has a potential fix to this issue if anyone is still running into this.
