### ISSUE TITLE
how to configure to use .env var directly on lib startup

### ISSUE THREAD

**Issue by sejidjorge** [ryanto/next-s3-upload#38]
all .env var used in my project are defined by STS and I am not able to use

**Comment by ryanto** [comment]
Hi there!

I'm not familiar with STS, do you get any sort of error?

How do you use other ENVs in your application?

**Comment by sejidjorge** [comment]
I need to pass bucketName, sessionToken, secretKey, accessKey on each upload because we're using temporary variables (https://docs.aws.amazon.com/pt_br/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) and env vars do not make sense for us.

something like:
`await uploadToS3(file, bucketName, sessionToken, accessKey, secretKey)`

Is it possible?
Tks

**Comment by sejidjorge** [comment]
I just realized that our method is insecure, I'll do some more tests to see if I can solve these problems since the variables are visible in the request

**Comment by sejidjorge** [comment]
We made a change in our method and now when uploading, a call is made to the Next API and it calls the variables and loads the images in the sdk

**Comment by ryanto** [comment]
Awesome! Glad to hear you got something working. I'm going to close this issue but feel free to reopen if there's anything that's preventing you from uploading.
