### ISSUE TITLE
Option to pass a config file to resize image.

### ISSUE THREAD

**Issue by heteibako** [ryanto/next-s3-upload#45]
Would be a great addition to be able to pass an optional config object to resize huge files. Maybe with sharp(?)

**Comment by ryanto** [comment]
Hi there!

Unfortunately the files are uploaded directly to S3 and they never touch the next app or server. So we don't really have a good point where it makes sense to run sharp and process an image.

I'd recommend using a service like https://imgix.com/ which will let you resize the images after they have been uploaded to S3. This is what we do in our app and it works great.

**Comment by heteibako** [comment]
Hi Ryan,
Thanks for getting back.
I have solved this with a 3rd party package (react-resize I think) on the client side. 
So I basically I made it work for my own needs. 😊

**Comment by ryanto** [comment]
Awesome! That's great to hear. I'll tell people about that package if they ask in the future.
