### ISSUE TITLE
S3 URL file is downloaded instead of opening on the tab

### ISSUE THREAD

**Issue by vusaalab** [ryanto/next-s3-upload#46]
Hi There!

when I click s3 URL file is downloaded instead of opening on the tab, How to fix this?

**Comment by ryanto** [comment]
By default this should work if you are uploading an image with an extension like `.jpg`, `.png`, or any other common image format.

There's a few things that could mess this up though, so we could have a bug in the library.

If you could answer these questions it will help us debug what's going on.

1. How are you clicking the S3 url? Are you right-clicking an image and selecting "open in new tab" or are you clicking a link to open the image in a new tab?
2. Are you using a [custom key](https://next-s3-upload.codingvalue.com/s3-file-paths) function to rename the file after upload?
3. What is the extension of the file you are uploading?

**Comment by vusaalab** [comment]
Thank you for the replay,

1. I do both ways, sometimes right-click open or click the URL any way it is downloading.
   https://s3.ap-southeast-1.amazonaws.com/blockstars.io/assets/00825690-ddab-464d-82f2-3a6c5cdd71b6/bigc.jpg
2. this is how i Implemented

    ```
      import { APIRoute} from 'next-s3-upload';
      import { v4 as uuidv4 } from 'uuid';
      
      const S3_UPLOAD_FOLDER = process.env.S3_UPLOAD_FOLDER
      
      export default APIRoute.configure({
          key(req, filename) {
              return `${S3_UPLOAD_FOLDER}/${uuidv4()}/${filename}`;
          },
      });
     ```

3. jpeg, png, mp4, etc..

**Comment by ryanto** [comment]
Ok great! Thanks for getting back.

Everything looks good there, so maybe there's some library code we can improve. I'll use your image and write a few tests cases and see what I find.

In the mean time you might be able to fix this by editing your metadata in the AWS console: ttps://docs.aws.amazon.com/AmazonS3/latest/userguide/add-object-metadata.html

**Comment by vusaalab** [comment]
Problem fixed, We manually edited the file and forget a put file type

    `var image = new File(parts, 'sample.jpg', {
        type: "image/jpeg"  // forget to add file type
    });`

**Comment by ryanto** [comment]
Oh gotcha, thanks for the update. 

Are you editing the image on the client? I'd  love to know what libraries you are using since people have asked me about the sort of thing in the past.
