### ISSUE TITLE
Possible security issue with STS getFederationToken

### ISSUE THREAD

**Issue by anguskeatinge** [ryanto/next-s3-upload#49]
Hi I was looking into using this and noticed that you were passing the AccessKeyId, SecretAccessKey, and SessionToken to the frontend.

The method you're using AWS sts getFederationToken is documented here: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html

The docs say "this call is appropriate in contexts where those credentials can be safely stored, usually in a server-based application"

Can you please explain why you're using this method instead of getting a signed URL from s3?

**Comment by vunhutien** [comment]
Hi @ryanto,
I have same concern with @anguskeatinge. Here is the response of the upload function, that return a toke contains full information, including accessKey and secretkey.
API api/s3-upload?filename=
![image](https://user-images.githubusercontent.com/37206017/159188181-e4bf8ebd-7d1a-4daa-abbb-f1d8e108fb44.png)

And the api response
![image](https://user-images.githubusercontent.com/37206017/159188041-6bccedac-f7ff-464c-8967-d1e9fd4b3bc3.png)

I think this api response can be seen by end user. Am I configuring anything wrongly?

**Comment by vunhutien** [comment]
Thanks @ryanto for your explanation and thank to your effort to build this lib.
