### ISSUE TITLE
missingEnvs reporting false negatives

### ISSUE THREAD

**Issue by nealbailly** [ryanto/next-s3-upload#50]
Context:
AWS Serverless,
node v.14
NextJS 12

Similar to issue #32 I'm seeing a problem with false positive in the missingEnvs function in my environment, which is AWS Lambda (deployed by Serverless) using Node 14 and Next 12.

Next S3 Upload: Missing ENVs S3_UPLOAD_KEY, S3_UPLOAD_SECRET, S3_UPLOAD_REGION, S3_UPLOAD_BUCKET

When calling the function it is reporting that I am missing all environment variables needed to use S3.

I created the test function you recommended on issue #32:

----
```
// pages/api/test-missing-env.js

let missingEnvs = () => {
  let keys = [
    'S3_UPLOAD_KEY',
    'S3_UPLOAD_SECRET',
    'S3_UPLOAD_REGION',
    'S3_UPLOAD_BUCKET',
  ];
  return keys.filter(key => !process.env[key]);
};

export default function(req, res) {
  res.status(200).json({ missing: missingEnvs() });
}
```
---

```
This returns an array of missing variables:
[
    'S3_UPLOAD_KEY',
    'S3_UPLOAD_SECRET',
    'S3_UPLOAD_REGION',
    'S3_UPLOAD_BUCKET',
 ]

```

Then I created a second test function using a different reference method on the environment variables:

---
```
// pages/api/test-again-missing-env.js

let missingEnvs = (): string[] => {
  let keys = [];
  if (!process.env.S3_UPLOAD_KEY) keys.push('S3_UPLOAD_KEY')
  if (!process.env.S3_UPLOAD_SECRET) keys.push('S3_UPLOAD_SECRET')
  if (!process.env.S3_UPLOAD_REGION) keys.push('S3_UPLOAD_REGION')
  if (!process.env.S3_UPLOAD_BUCKET) keys.push('S3_UPLOAD_BUCKET')
  return keys;
};
```
---

This returns an empty array:
`[]`

I also ran a test where I wrote out the values on a test endpoint using the second variable reference method and saw the actual values in my response, so I know they exist and are correct.

S3_UPLOAD_KEY: *****
S3_UPLOAD_SECRET: *****
S3_UPLOAD_REGION: *****
S3_UPLOAD_BUCKET: *****

The problem with the missingEnvs function and why it is not recognizing the values is that the function uses square brackets to reference the process.env values.   

With Next.js, the environment variables are created at build time and are stored, but not as objects.  You should only reference them with the method process.env.UPLOAD_KEY, not process.env[UPLOAD_KEY] or const {UPLOAD_KEY} = process.env.   

Because in Next.js process.env is not actually an object, referencing values in an array construct or by dereferencing doesn't work (in all cases).

A simple change to your function to read as above using process.env.VARIABLE_NAME construct will solve my problem, and likely the problem reported on issue #32 

See NOTE on https://nextjs.org/docs/basic-features/environment-variables for further explanation of the process.env variables in Next.js, especially the following note:

Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. This means that process.env is not a standard JavaScript object, so you’re not able to use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). Environment variables must be referenced as e.g. process.env.PUBLISHABLE_KEY, not const { PUBLISHABLE_KEY } = process.env.

**Comment by ryanto** [comment]
Awesome! Thanks for debugging this.

I wonder why this only happens on AWS? Either way I think we should change the code to use your method of checking and pushing the missing ENVs to an empty array.

Thanks again for getting to the bottom of this and finding a fix. I'll open a PR shortly.

**Comment by ryanto** [comment]
Ok this is published in `0.1.8`, give it a shot and let me know how it goes.

**Comment by nealbailly** [comment]
Bingo!  The misingEnvs function now returns a correct response when used on Lamba@Edge deployed by the [Next.js Serverless component](https://www.serverless.com/plugins/serverless-nextjs-plugin).  

Side note:  I am configuring API_ROUTE with a custom **uploadPath** that uses the request referer to do a DB lookup and rewrite the upload destination based on found object.  With a small change to CloudFront at AWS to allow the referer header to pass through CloudFront, everything is working great).

Thanks for the quick turn-around!

**Comment by ryanto** [comment]
Glad to hear it worked!

> Side note: I am configuring API_ROUTE with a custom uploadPath that uses the request referer to do a DB lookup and rewrite the upload destination based on found object. With a small change to CloudFront at AWS to allow the referer header to pass through CloudFront, everything is working great).

Sounds interesting! Were you able to do it easily, or would any additional support from this library have helped? 

I'd love to see an example of your API route to get a better picture.
