### ISSUE TITLE
Does the library upload straight to S3?

### ISSUE THREAD

**Issue by michaltaberski** [ryanto/next-s3-upload#52]
Hi,

Currently, I am uploading files to S3 using `multerS3Storage`. That works fine, but after deploying code to Vercel cloud I am hitting an issue with max payload size of 5MB (https://vercel.com/docs/concepts/limits/overview#serverless-function-payload-size-limit). 

So I would like to ask you as I don't understand the lib 100%. Is the lib uploading files stright to S3 and omits API or it requires proxing through API?

**Comment by ryanto** [comment]
I can't speak for multerS3Storage, that is a different library.

This library (next-s3-upload) uploads directly to S3 and does not proxy through Vercel's API. Please let me know if that clears up your question.

**Comment by michaltaberski** [comment]
Yes, that's exactly what I was asking about. Thanks for a fast anwser. I will test your solution right away.

**Comment by ryanto** [comment]
Ok great! Let me know if you run into any issues or anything in the setup process is confusing.
