### ISSUE TITLE
Plans to support Min.io

### ISSUE THREAD

**Issue by timothymiller** [ryanto/next-s3-upload#53]
Great library!

I would like to see this library support Min.io, as it has an S3-compatible API, it shouldn't be too much lift to support it.

Thank you!

**Comment by ryanto** [comment]
Hi there! Thanks for the suggestion, but unfortunately I do not have time to add support for Min into this library.

**Comment by ryanto** [comment]
Ok support for Non-AWS hosts, like min.io, is now available in `0.2.8`. 

Docs here: https://next-s3-upload.codingvalue.com/other-providers
