### ISSUE TITLE
Upload images via copy & paste instead of file system

### ISSUE THREAD

**Issue by p-christ** [ryanto/next-s3-upload#63]
hey! 

Is it possible for people to upload images via copy & paste instead of opening up the file system to provide the image?  That would be SO useful!!

**Comment by johnmasonwilliams** [comment]
You can use [your own File Input](https://next-s3-upload.codingvalue.com/custom-file-input) like it states in the docs to do this while still using `next-s3-upload` to manage the file uploads. This would allow you to use either another package or your own solution for a copy & paste file upload.

Implementing a feature rich File Input might be a little bit out of this project's scope but it would be nice to have everything in one place.

Hopefully this helps!

**Comment by p-christ** [comment]
makes sense, thanks a lot!
