### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by iamindrazulfi** [ryanto/next-s3-upload#68]
Hey there, i keep got this problem,
I have setup as docs regarding the CORS.
But stills.

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/78650493/163697461-0f5ffa3f-f0ec-4407-b9f0-19e38a44f876.png">

**Comment by ryanto** [comment]
Hi there.

Do you have a link to your upload page where I can take a look?

**Comment by ryanto** [comment]
Hi there, I haven't heard from you so I'm going to close this issue :)

Feel free to share a link if you'd like me to take a look.
