### ISSUE TITLE
Console always return error: 'Unsupported body payload object'

### ISSUE THREAD

**Issue by julesberto** [ryanto/next-s3-upload#69]
**The console always returned the below error everytime I try to submit to s3. I need help please anyone**

Unhandled Runtime Error
Error: Unsupported body payload object

Call Stack
ManagedUpload.self.fillQueue
node_modules\aws-sdk\lib\s3\managed_upload.js (92:0)
ManagedUpload.send
node_modules\aws-sdk\lib\s3\managed_upload.js (201:0)
eval
node_modules\aws-sdk\lib\util.js (839:0)
new Promise
<anonymous>
ManagedUpload.promise
node_modules\aws-sdk\lib\util.js (831:0)
_callee$
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (1032:0)
tryCatch
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (124:0)
Generator.invoke [as _invoke]
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (338:0)
Generator.eval [as next]
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (176:0)
asyncGeneratorStep
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (8:0)
_next
node_modules\next-s3-upload\dist\next-s3-upload.esm.js (30:0)

**Comment by ryanto** [comment]
Can you share your code that's uploading the file?

**Comment by ryanto** [comment]
Hi there, I haven't heard from you so I'm going to close this issue :)

Feel free to share you code at anytime in the future!
