### ISSUE TITLE
Securing the Next.js API Route

### ISSUE THREAD

**Issue by jere-co** [ryanto/next-s3-upload#70]
Thanks for the great looking repository. 

It would be great if the documentation could include an example about how to use the `APIRoute` with custom authentication. 

What I'm trying to achieve personally is to use `withIronSessionApiRoute` as in the example here https://github.com/vercel/next.js/blob/canary/examples/with-iron-session/pages/api/events.ts

The `next-s3-upload` would otherwise allow anyone to use the uploader, so this should definitely be documented from the beginning.

**Comment by ryanto** [comment]
You want to do something like this: https://gist.github.com/ryanto/1db2c41465ac3432d9eec18b18257111

**Comment by jere-co** [comment]
Thanks. Managed to get it to work without TypeScript warning with the below. Closing. 

```TS
import { withIronSessionApiRoute } from 'iron-session/next'
import { sessionOptions } from '@lib/session'

import { APIRoute } from 'next-s3-upload'

import type { NextApiRequest, NextApiResponse } from 'next'

const uploadHandler = APIRoute.configure({})

const s3UploadAPI = (req: NextApiRequest, res: NextApiResponse) => {
  const { session } = req
  const isLoggedIn = session?.user?.isLoggedIn ?? false

  if (isLoggedIn) {
    return uploadHandler(req, res)
  }

  res.status(403).json({ message: 'Forbidden' })
}

export default withIronSessionApiRoute(s3UploadAPI, sessionOptions)
```
