### ISSUE TITLE
Add an option to specify custom headers 

### ISSUE THREAD

**Issue by zernie** [ryanto/next-s3-upload#71]
It'd be nice to be able to pass a `headers` object to `useS3Upload` hook. Other fetch options like `method` could be useful as well.

Why? For example, Blitz.js requires all incoming API requests to have an anti-csrf header.

Thanks!

**Comment by ryanto** [comment]
Yup, good idea. Can you take a look at this issue: https://github.com/ryanto/next-s3-upload/issues/61 and let me know if this idea would work for you?

I think in an upcoming release I'll change the method to 'POST' by default. Is there any specific reason you want to modify the method?

**Comment by zernie** [comment]
@ryanto yep, that API looks good! As for the method, it just makes sense to use POST for the request that changes data on the server.|

Thank you!

**Comment by ryanto** [comment]
Ok glad to hear it'll work.

Just FYI there is no data changed on the server, that's why we're using a GET.

**Comment by ryanto** [comment]
Ok this is all set!

I changed the request to be POST, and added the ability to send json + headers.

It's released in version `0.2.1`. Here are the docs for modifying headers: https://next-s3-upload.codingvalue.com/s3-file-paths#headers

Let me know if you run into any trouble.

**Comment by zernie** [comment]
Thanks! 🎉
