### ISSUE TITLE
Support private buckets and getSignedUrl for uploaded images

### ISSUE THREAD

**Issue by LorenzoGala** [ryanto/next-s3-upload#72]
Hey!
Are you going to implement a way to provide support for private buckets and to implement a way to retrieve a signedUrl for the uploaded images?

**Comment by ryanto** [comment]
Great question!

What would you like to see in terms of an API for generating signed URLs? Are you generating these URLs in API routes? gSSP? gSP? Would love to hear more about where you need them.

**Comment by iDavidB** [comment]
My apologies if this is not what @LorenzoGala meant, or if I misunderstand something
 
In the policy we add to our bucket, we basically make the complete bucket readable through getObject? I assume because that makes the `url` property always be defined? Haven’t tested this yet as I have been busy. 

If so, would it be possible to generate a signed url for the Location so that we don’t need to allow getObject on our complete bucket?

**Comment by ryanto** [comment]
Yup, that sounds right!

Right now the getting started guide is very basic, but it's not required if you want to use another approach. For example, you could change the policy and use signed urls that grant temporary access to files in your bucket.

I started working on a guide for how to best set up private uploads, but got a little busy with work. Hopefully I'll have something in a few weeks

**Comment by iDavidB** [comment]
That would be great @ryanto! Would you mind pointing me in the right direction on how to handle this? Some AWS docs would already be a great help.

We used this package source and converted it to work with Blitz for our project.

**Comment by LorenzoGalassi** [comment]
Sorry if i jump back in the conversation with a different account but i changed it for working reasons :)

After a bit of research i ended up using the next backend by creating a file in
`pages/api` called `s3-upload-url.js` with the following code:
<img width="741" alt="raycast-untitled" src="https://user-images.githubusercontent.com/104760516/172546588-cd330553-420b-4615-906e-4ca6b5c6936d.png">

And then calling it in a component:
<img width="920" alt="raycast-untitled (5)" src="https://user-images.githubusercontent.com/104760516/172548115-15b5ff40-c594-4136-a177-de5dadee472a.png">

Of course this is a basic usage, can be improved but works fine!

PS: remember to setup a `.env` file on the root of the project with the requested informations regarding the bucket!

**Comment by LorenzoGalassi** [comment]
Update: I've added an extra api for the generation of sharable presigned urls with expiration time setted to one week.
You can find the code and more informations in my public boilerplate for Next.js: [https://github.com/LorenzoGalassi/nextjs-boilerplate](https://github.com/LorenzoGalassi/nextjs-boilerplate)
