### ISSUE TITLE
How to handle file and user verification? 

### ISSUE THREAD

**Issue by dasveloper** [ryanto/next-s3-upload#79]
Is there a way to provide file validation on the server-side using this package such as file size, file type, and max files per upload? I see we can allow certain file types via the IAM user policy but I'd like to provide a useful error message response.

Similarly, I'd like to check if the user is logged in. In the custom path name docs there is this example:
```
// pages/api/s3-upload.js
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  async key(req, filename) {
    let user = await getUserFromAuthToken(req.headers.authorization);

    return `users/${user.id}/${filename}`;
  }
});
```
However, if user is not logged in the user.id would be undefined. I'd like to check that user exists and if not return an error response, but the api response isn't available here.

Is there a place to add these checks?

**Comment by ryanto** [comment]
For user verification you can wrap the next-s3-upload handler in your own auth check and verify the user before you call it. Check out this gist and let me know if you have any questions: https://gist.github.com/ryanto/1db2c41465ac3432d9eec18b18257111


File validation is a little tricky. Uploads go directly to S3, they don't pass through your next.js server. So you won't have access to the file in next.

You could use a combo of client side validation, s3 policy rules, and AWS lamda's post upload hook to do specific validation checks that require the actual file.

**Comment by ryanto** [comment]
Hey there, haven't heard anything so I'm going to close this issue. Feel free to follow up if you have any more questions.
