### ISSUE TITLE
Is there a way to use custom environment variables for the creds? 

### ISSUE THREAD

**Issue by ParthGandhi** [ryanto/next-s3-upload#81]
I want to rename the creds from `S3_UPLOAD_SECRET` etc to something more specific to our use case.
Also it might be useful to allow  passing through some options to the underlying S3 upload call.

**Comment by ryanto** [comment]
Currently this is not supported. Maybe if your webhost allows you to alias ENV vars you can setup something with a different name.

In theory we should be able to add this feature, but right now it's not a high priority so unfortunately it could take me a while.

**Comment by ryanto** [comment]
Hey sorry for the long delay/reply. I don't think I'm going to be able to get to this issue anytime so and I'd recommend using the default ENVs from the library for now. Going to close this issue, but let me know if you have any other thoughts.
