### ISSUE TITLE
Is there a way to compress file image before it is uploaded

### ISSUE THREAD

**Issue by ibrahimyaacob92** [ryanto/next-s3-upload#82]

**Comment by ohager** [comment]
Actually, compressing modern image formats won't work, as they are already highly compressed. You can pre-process the images like reducing quality and dimensions, or even convert to a better format, like jpg,png to webp... this depends always on the format and your use case. (btw: svg is text only, and best compressed by gzip or brotli)

an option is mentioned here #45, and I already used [browser-image-compression](https://www.npmjs.com/package/browser-image-compression) successfully.

**Comment by ryanto** [comment]
Thanks for answering this @ohager! Great suggestion!
