### ISSUE TITLE
Chrome Large File Issue

### ISSUE THREAD

**Issue by jhochgrevetsd** [ryanto/next-s3-upload#86]
Hey thanks for such a great package!! I am having some issues when uploading larger file (over 1Gish) when using Chrome (all other browsers seem to work) here is the error: net::ERR_CONNECTION_RESET

Is there anything I can do to avoid this? It seems to happen more times than not, but occasionally a file works without the error.

**Comment by ryanto** [comment]
Odd! I know we tested large files, but that was a while ago and there have been a few changes to the aws-sdk version since then.

Does it work in chrome w/ an incognito window?

I'll give this a test in with a large file in chrome and let you know how it goes.

**Comment by jhochgrevetsd** [comment]
@ryanto Great question. I did not check in Incognito (rookie mistake) I will test this also.

**Comment by jhochgrevetsd** [comment]
@ryanto Tested in chrome with the same error. I was specifically using a 1.6GB .ZIP file

Here is our implementation. Nothing fancy. We are not uploading on change but rather on submit:

`        let { url } = await uploadToS3(data.plan, {
          endpoint: {
            request: {
              body: {
                projectEmail: data.email
              }
            }
          }
        })`

Then our API file:
`import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
  async key(req, filename) {
    let projectEmail = req.body.projectEmail;

    return `plans/${projectEmail}/${filename}`;
  }
});`

**Comment by ryanto** [comment]
Ok cool! Thanks for the code samples, that should totally work so I think there's a bug somewhere :)

I just tested this with a 1.5gb file and a 14gb file in chrome. They both worked.

However, I did notice that we only give the frontend one hour to finish the upload (after an hour we revoke access). Is it possible your uploads are taking over an hour?

Also, when the upload fails you'll probably have a request in your network tab that triggered the failure (it'll be red and probably the last request or so). Could you share the response from AWS for that request, sometimes they give helpful error messages.

**Comment by jhochgrevetsd** [comment]
@ryanto Sorry it took me a while to get back! LOTS of projects right now! It's odd...I actually do not have any red in my network tab. Everything seems to be returning a 200; however, here is a screenshot of the error I am still getting. This was for a 1.4GB .ZIP file:
![Screen Shot 2022-08-31 at 9 59 13 AM](https://user-images.githubusercontent.com/87723081/187697628-61786a5f-a1c6-4c0e-bc1d-54b276194213.png)

**Comment by ryanto** [comment]
Thanks! About how long after the upload started did you get that error?

Also mind screenshoting the "Headers" tab as well, sometimes there's some good info in there.

**Comment by ryanto** [comment]
Hey @jhochgrevetsd I'm doing some issue closing on this repo, so I'm going to close this one. 

Let me know if you're still running into this or want any help debugging.
