### ISSUE TITLE
Getting 'InvalidClientTokenId: The security token included in the request is invalid' error

### ISSUE THREAD

**Issue by nik32** [ryanto/next-s3-upload#87]
I have set up the AWS account as given in docs but I am getting this error constantly. Kindly help!! Quick help would be really appreciated @ryanto!!!

**Comment by ryanto** [comment]
When this happens it's usually one of two things:

* You haven't setup the account correctly
* You've got the environment variables set wrong

**Comment by nik32** [comment]
Hey thanks @ryanto!!! Maybe seems I was doing something wrong in the setup, so re-did it and it worked!!! Thanks a lot

**Comment by ryanto** [comment]
Oh awesome, glad to hear you were able to get it working!
