### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by iadefidipe** [ryanto/next-s3-upload#92]
I  get this error when I try uploading files in production: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

/api/s3-upload
`export { APIRoute as default } from "next-s3-upload";`

/upload function
`
import { useS3Upload } from "next-s3-upload"
import { toast } from "react-toastify"

function renameFile(originalFile: any) {
    const newName = (+new Date()).toString()
    return new File([originalFile], newName, {
      type: originalFile.type,
      lastModified: originalFile.lastModified,
    })
  }

   let handleFileChange = async (event: any) => {
    const id = toast.loading("Uploaing Lesson Video")

    try {
      let renamed = renameFile(event.target.files[0])
      console.log("renamed file", renamed)

      const { url } = await uploadToS3(renamed)
      if (url !== undefined) {
        setVideo(url)
        toast.update(id, {
          render: "Video Uploaded!",
          type: "success",
          isLoading: false,
          autoClose: 3000,
        })
      }
    } catch (err) {
      console.error(err)
      toast.update(id, {

        render: `Something went wrong : ${err}`,
        type: "error",
        isLoading: false,
        autoClose: 3000,
      })
    }
  }`

 Everything thing works well when I upload files in development or locally. I dont know could be the problem, please help

screens of network req in browser
![Screenshot (7)](https://user-images.githubusercontent.com/61972317/188759048-067bdfc9-0517-4284-ad1e-825867687888.png)
![Screenshot (6)](https://user-images.githubusercontent.com/61972317/188759053-0425a486-2c2c-4791-b141-5e1a35b3312d.png)
![Screenshot (5)](https://user-images.githubusercontent.com/61972317/188759054-9da5da98-7858-4219-88f8-a9527d3d979e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/61972317/188759055-13ac2f66-78fb-433d-9c5a-ac2d4cdb26e0.png)
![Screenshot (9)](https://user-images.githubusercontent.com/61972317/188759056-d60bd094-2c3e-4ba8-8761-a2a9aaf53e27.png)
![Screenshot (8)](https://user-images.githubusercontent.com/61972317/188759057-2b841cb2-16d7-468c-aed5-d09408ebe999.png)

**Comment by ryanto** [comment]
Hi there!

This is usually caused by your production server not exposing the api route at `/api/s3-upload` correct.

What happens when you directly visit the API route in production. For example, my-production-site.com/api/s3-upload. Does it load the API route or another page?

**Comment by iadefidipe** [comment]
yh, it is loading another page..

**Comment by iadefidipe** [comment]
Do you have any idea why?

**Comment by ryanto** [comment]
I'm not sure why, but this most likely has something to do with how you setup your app's production deployment. Are you using a [custom basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath) or any kind of url redirecting/rewriting in production?

**Comment by iadefidipe** [comment]
I found the problem was with the deployment server not accessing next js API routes... Thanks

**Comment by 0mar2090** [comment]
> Encontré que el problema era que el servidor de implementación no accedía a las siguientes rutas API js ... Gracias

si era eso gracias xd
