### ISSUE TITLE
I have an Error when I use Korean in file path.

### ISSUE THREAD

**Issue by JongWooBAE** [ryanto/next-s3-upload#94]
I have to upload image file to S3.

It is OK, when I use English in path.

But when I use Korean in the path, this error is occurred.

this error is occurred in VScode.
![image](https://user-images.githubusercontent.com/63835879/189009197-4272b8b5-1789-4148-a1d0-c13550709c6e.png)

And this is my code. I put the .env file exactly.

components/upload.tsx
```
import { useState } from "react";
import { useS3Upload } from "next-s3-upload";

export default function UploadImages() {
  const [urls, setUrls] = useState([]);
  const { uploadToS3 } = useS3Upload();

  const handleFilesChange = async ({ target }) => {
    const files = Array.from(target.files);

    try{
      for (let index = 0; index < files.length; index++) {
        const file = files[index];
        const { url } = await uploadToS3(file, {
          endpoint: {
            request: {
              body: {
                id: '배종우'  // Korean name I want to put in path
              }
            }
          }
        });
        console.log(1);
  
        setUrls(current => [...current, url]);
      }  
    } catch(err){
      console.log(err)
    }
  };

  return (
    <div>
      <input
        type="file"
        name="file"
        multiple={true}
        onChange={handleFilesChange}
      />

      <div>
        {urls.map((url, index) => (
          <div key={url}>
            File {index}: ${url}
          </div>
        ))}
      </div>
    </div>
  );
}
```

pages/api/s3-upload.ts
```
import { APIRoute } from "next-s3-upload";

export default APIRoute.configure({
    key(req, filename){
        let id = '아' // 아 is Korean to test uploading korean
        return `${id}/${filename}`;
    }
});
```
pages/index.tsx
```
import type { NextPage } from 'next'
import UploadImages from '../components/upload'

const Home: NextPage = () => {
  return (
    <div>
      <UploadImages />
    </div>
  )
}

export default Home
```

I must input Korean in the file path. Please help.

**Comment by ryanto** [comment]
Interesting, thanks for the report!

I'm not sure how to best go about fixing this. I pulled up the docs on AWS file naming and they have (a very basic) list of safe characters.

<img width="573" alt="Screen Shot 2022-09-08 at 11 51 42 AM" src="https://user-images.githubusercontent.com/89411/189168208-740649d6-2314-4273-a5b5-b69e136dfecc.png">

**Comment by ryanto** [comment]
Hey I haven't heard back from you in a while. I'm going to close this issue, but feel free to comment if you think there's still a problem here!
